dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
    image_templates:
      - julianli/onedump
      - "julianli/onedump:{{ .Tag }}"